"""Human-facing agent messages. Never expose raw provider exceptions."""
TEXT = {
    "uz": {
        "welcome": "🎙 Ernest — ovozli yordamchi\nO‘zbekcha, ruscha yoki inglizcha yozing/ovoz yuboring. Vazifa, odat, loyiha yoki pul yozuvini tayyorlayman. Faqat tasdiqlash tugmasidan keyin bajaraman. Javobsiz qoldirsangiz Inbox’da saqlanadi.\n\nOvoz, matn va mos yozuvlaringizning qisqa ro‘yxati tanlangan AI xizmatiga yuboriladi. Audio ErnestOS serverida saqlanmaydi; matn va amal tarixi saqlanadi. Maxfiy parol/karta raqamlarini yubormang.",
        "consent": "Roziman, agentni ishlatish", "consented": "Tayyor. Endi ovoz yoki matn yuboring. /inbox — saqlangan buyruqlar. /agent — yo‘riqnoma.",
        "confirm": "✅ Tasdiqlash", "edit": "✏️ Tuzatish", "cancel": "❌ Bekor qilish", "keep": "📥 Inbox’da qoldirish", "retry": "🔄 Qayta tahlil",
        "inbox": "📥 Inbox", "empty": "Inbox hozir bo‘sh.", "more": "Keyingi", "new": "➕ Yangi buyruq", "close": "Yopish",
        "processing": "🎧 Qabul qilindi. Tahlil qilyapman…", "ready": "Shunday bajarilsinmi? Hali hech narsa o‘zgarmadi.",
        "executed": "✅ Bajarildi. Qayta bosish takroriy yozuv yaratmaydi.", "cancelled": "Bekor qilindi. Hech narsa bajarilmadi.",
        "kept": "📥 Inbox’da qoldi. Keyin /inbox orqali qaytishingiz mumkin.",
        "edit_prompt": "Shu buyruq uchun tuzatishni matn yoki yangi audio bilan yuboring. Masalan: «Ertaga emas, juma kuni soat 10 da». Yangi mustaqil buyruq uchun /agent yozing.",
        "private": "Ovozli agentni bot bilan shaxsiy chatda ishlating.", "heard": "Sizning xabaringiz", "inbox_status": "Inbox’da saqlangan; bajarilmagan.",
        "disabled": "Agent hali yoqilmagan. Oddiy bot funksiyalari ishlashda davom etadi.",
        "failure": "Bajarilmadi. Buyruq Inbox’da saqlandi. Tuzating yoki qayta urinib ko‘ring.",
        "provider_limit": "AI xizmatining limiti tugadi. Keyin qayta tahlil qiling; pullik xizmatga avtomatik o‘tmaydi.",
        "daily_limit": "Bugungi agent limiti tugadi. Buyruq saqlandi, ertaga qayta tahlil qilish mumkin.",
        "provider_not_configured": "AI kaliti ulanmagan yoki yaroqsiz. Administrator sozlashi kerak.",
        "provider_unavailable": "AI xizmati hozir javob bermadi. Keyin qayta urinib ko‘ring.",
        "consent_required": "Avval /agent orqali AI xizmatiga yuborishga rozilik bering.",
        "stale_draft": "Bu eski tasdiq. Inbox’dan buyruqning yangi ko‘rinishini oching.",
        "stale_target": "Yozuv tayyorlashdan keyin o‘zgargan. Qayta tahlil qilib yangi ko‘rinishni tasdiqlang.",
        "not_found": "Yozuv topilmadi yoki sizga tegishli emas.", "forbidden": "Bu jamoa yozuvini o‘zgartirishga ruxsatingiz yo‘q.",
        "protected_item": "Bu odat alohida moduldan boshqariladi; uning ekranidan foydalaning.",
        "timer_required": "Bu amal uchun avval belgilangan taymerni yakunlang.",
        "draft_expired": "Tasdiq 24 soatdan oshdi. Avval qayta tahlil qiling.",
        "audio_too_long": "Audio 2 daqiqadan oshmasin.", "invalid_audio": "Audio o‘qilmadi. OGG, WebM, MP3, M4A yoki WAV (10 MB gacha) yuboring.",
        "audio_decoder_missing": "Serverga audio o‘quvchi o‘rnatilmagan. Matn yuborishingiz mumkin.",
        "empty_audio": "Ovozdan matn olinmadi. Qayta yozing yoki matn kiriting.",
        "invalid_plan": "Buyruq ishonchli ajratilmadi. Nima va qayerga kiritishni aniqroq ayting.",
        "processing_interrupted": "Tahlil uzildi. Matn bo‘lsa qayta tahlil qiling; bo‘lmasa audioni qayta yuboring.",
        "not_ready": "Bu buyruq tasdiqlashga tayyor emas. Inbox’dan ko‘rib chiqing.",
    },
    "ru": {
        "welcome": "🎙 Ernest — голосовой помощник\nОтправьте голос или текст на узбекском, русском или английском. Подготовлю задачи, привычки, проекты и записи финансов. Выполню только после нажатия подтверждения. Без ответа черновик остаётся во Входящих.\n\nАудио, текст и краткий список подходящих записей передаются выбранному AI-провайдеру. ErnestOS не хранит аудио; текст и история действий сохраняются. Не отправляйте пароли и номера карт.",
        "consent": "Согласен, включить помощника", "consented": "Готово. Отправьте голос или текст. /inbox — черновики. /agent — помощь.",
        "confirm": "✅ Подтвердить", "edit": "✏️ Исправить", "cancel": "❌ Отменить", "keep": "📥 Оставить", "retry": "🔄 Разобрать снова", "inbox": "📥 Входящие", "empty": "Пока пусто.", "more": "Далее", "new": "➕ Новая команда", "close": "Закрыть",
        "processing": "🎧 Принято. Обрабатываю…", "ready": "Выполнить так? Пока ничего не изменено.", "executed": "✅ Выполнено. Повторное нажатие не создаст дубликат.", "cancelled": "Отменено. Ничего не выполнено.", "kept": "📥 Сохранено. Вернуться: /inbox.",
        "edit_prompt": "Отправьте исправление текстом или голосом. Например: «Не завтра, а в пятницу в 10». Для отдельной команды: /agent.", "private": "Используйте помощника в личном чате с ботом.", "heard": "Ваше сообщение", "inbox_status": "Сохранено во Входящих, не выполнено.",
        "disabled": "Помощник пока выключен. Обычные функции бота работают.", "failure": "Не выполнено. Черновик сохранён: исправьте или повторите.", "provider_limit": "Достигнут лимит AI. Повторите позже; платного переключения нет.", "daily_limit": "Дневной лимит исчерпан. Черновик сохранён.", "provider_not_configured": "AI-ключ отсутствует или недействителен. Обратитесь к администратору.", "provider_unavailable": "AI не ответил. Повторите позже.", "consent_required": "Сначала дайте согласие через /agent.", "stale_draft": "Старое подтверждение. Откройте новую версию во Входящих.", "stale_target": "Запись изменилась. Заново разберите и подтвердите команду.", "not_found": "Запись не найдена или недоступна.", "forbidden": "Недостаточно прав для этой командной записи.", "protected_item": "Эта привычка управляется отдельным модулем.", "timer_required": "Сначала завершите таймер.", "draft_expired": "Прошло более 24 часов. Разберите команду заново.", "audio_too_long": "Аудио: не более 2 минут.", "invalid_audio": "Не удалось прочитать аудио. OGG, WebM, MP3, M4A, WAV — до 10 МБ.", "audio_decoder_missing": "На сервере нет аудиодекодера. Можно отправить текст.", "empty_audio": "Речь не распознана. Запишите снова или введите текст.", "invalid_plan": "Не удалось надёжно разобрать команду. Уточните действие и запись.", "processing_interrupted": "Обработка прервана. Повторите разбор текста или отправьте аудио снова.", "not_ready": "Команда ещё не готова к подтверждению.",
    },
    "en": {
        "welcome": "🎙 Ernest voice assistant\nSend voice or text in Uzbek, Russian or English. I prepare tasks, habits, projects and money entries, and execute only after you press Confirm. Unanswered drafts stay in Inbox.\n\nAudio, text and a short relevant record list are sent to the selected AI provider. ErnestOS does not retain audio; transcripts and action history are retained. Do not send passwords or card numbers.",
        "consent": "I agree, use assistant", "consented": "Ready. Send voice or text. /inbox — drafts. /agent — help.", "confirm": "✅ Confirm", "edit": "✏️ Correct", "cancel": "❌ Cancel", "keep": "📥 Keep in Inbox", "retry": "🔄 Re-analyze", "inbox": "📥 Inbox", "empty": "Inbox is empty.", "more": "Next", "new": "➕ New command", "close": "Close", "processing": "🎧 Received. Analyzing…", "ready": "Proceed with this? Nothing has changed yet.", "executed": "✅ Done. Repeated confirmation will not create duplicates.", "cancelled": "Cancelled. Nothing was executed.", "kept": "📥 Saved. Return with /inbox.", "edit_prompt": "Send a correction in text or voice, e.g. 'Friday at 10, not tomorrow'. For a separate command use /agent.", "private": "Please use the assistant in a private chat with the bot.", "heard": "Your message", "inbox_status": "Saved in Inbox; not executed.", "disabled": "Assistant is not enabled yet. Normal bot features still work.", "failure": "Not executed. Draft saved: correct it or try again.", "provider_limit": "AI quota reached. Try later; there is no paid fallback.", "daily_limit": "Daily assistant limit reached. Draft saved.", "provider_not_configured": "AI key is missing or invalid. Ask the administrator to configure it.", "provider_unavailable": "AI did not respond. Try later.", "consent_required": "Give consent through /agent first.", "stale_draft": "This confirmation is outdated. Open the latest Inbox draft.", "stale_target": "The record changed. Re-analyze and confirm the new proposal.", "not_found": "Record not found or not accessible.", "forbidden": "You cannot manage this team record.", "protected_item": "Use the dedicated screen for this derived habit.", "timer_required": "Finish the required timer first.", "draft_expired": "This proposal is over 24 hours old. Re-analyze first.", "audio_too_long": "Audio must be 2 minutes or shorter.", "invalid_audio": "Cannot read audio. Use OGG, WebM, MP3, M4A or WAV, up to 10 MB.", "audio_decoder_missing": "Server audio decoder is missing. Text still works.", "empty_audio": "No speech recognized. Re-record or type your command.", "invalid_plan": "Cannot reliably parse this command. Clarify the action and target.", "processing_interrupted": "Processing interrupted. Retry the transcript or resend audio.", "not_ready": "This draft is not ready to confirm.",
    },
}


EXTRA = {
    "uz": {"failure": "Buyruq bajarilmadi. Inbox’ni tekshiring va qayta urinib ko‘ring.", "invalid_text": "Matn yoki audiodan bittasini yuboring. Matn bo‘sh bo‘lmasin va 6000 belgidan oshmasin.", "invalid_fields": "Sana, vaqt, summa yoki boshqa maydon noto‘g‘ri. Tuzatishni aniq yozing.", "missing_fields": "Kerakli ma’lumot yetishmayapti. Nomi, summa yoki kirim/chiqim turini aniqlashtiring.", "invalid_action": "Bu amalni hozir bajarib bo‘lmaydi. Nima o‘zgartirishni aniqroq ayting.", "unknown_reference": "Qaysi yozuv nazarda tutilgani aniqlanmadi. Uning nomi, loyihasi yoki ID raqamini ayting.", "invalid_day": "Sana kelajakda bo‘lmasin va bir yildan eski bo‘lmasin.", "duplicate_target": "Bir yozuvga takroriy amallar tushdi. Bitta aniq o‘zgarish qilib ayting.", "too_many_edits": "Bu buyruq ko‘p marta tahrirlangan. Yangisini yuboring.", "concurrent_change": "Boshqa o‘zgarish bilan to‘qnashdi. Inbox’dan qayta urinib ko‘ring.", "input_language": "Xabar tili", "uz": "O‘zbekcha", "ru": "Ruscha", "en": "Inglizcha", "mixed": "Aralash", "unknown": "Aniqlanmadi"},
    "ru": {"failure": "Команда не выполнена. Проверьте Входящие и повторите.", "invalid_text": "Отправьте либо текст, либо аудио. Текст: от 1 до 6000 символов.", "invalid_fields": "Неверная дата, время, сумма или другое поле. Уточните исправление.", "missing_fields": "Не хватает данных: уточните название, сумму или доход/расход.", "invalid_action": "Это действие сейчас недоступно. Уточните изменение.", "unknown_reference": "Неясно, какая запись имеется в виду. Назовите проект, дату или ID.", "invalid_day": "Дата должна быть не в будущем и не старше года.", "duplicate_target": "Для одной записи указаны повторные действия. Уточните одно изменение.", "too_many_edits": "Слишком много исправлений. Создайте новую команду.", "concurrent_change": "Конфликт с другим изменением. Повторите через Входящие.", "input_language": "Язык сообщения", "uz": "Узбекский", "ru": "Русский", "en": "Английский", "mixed": "Смешанный", "unknown": "Не определён"},
    "en": {"failure": "Command not executed. Check Inbox and retry.", "invalid_text": "Send either text or audio. Text must contain 1–6000 characters.", "invalid_fields": "Invalid date, time, amount or other field. Clarify the correction.", "missing_fields": "Required information is missing: clarify the name, amount or income/expense type.", "invalid_action": "This action is not available. Clarify the requested change.", "unknown_reference": "Target is unclear. Specify its name, project, date or ID.", "invalid_day": "Date cannot be in the future or more than a year ago.", "duplicate_target": "Multiple actions target the same record. Specify one change.", "too_many_edits": "Too many revisions. Start a new command.", "concurrent_change": "Conflict with another change. Retry through Inbox.", "input_language": "Input language", "uz": "Uzbek", "ru": "Russian", "en": "English", "mixed": "Mixed", "unknown": "Unknown"},
}
for language, values in EXTRA.items():
    TEXT[language].update(values)


def tr(lang, key):
    words = TEXT.get(lang, TEXT["uz"])
    return words.get("disabled" if key == "agent_disabled" else key, words["failure"])
