"""Human-facing agent messages, always in the user's app language. Never expose raw provider errors."""
TEXT = {
    "uz": {
        "welcome": "🎙 Ernest — ovozli yordamchi\nOvozli xabar yoki matn yuboring: vazifa, odat, loyiha yoki pul yozuvini qo‘shaman, o‘zgartiraman yoki o‘chiraman. Faqat «Tasdiqlash» tugmasidan keyin bajaraman.\n\nOvoz va matn AI xizmatlariga (ElevenLabs, Groq, Google — AQSh) yuboriladi. Audio saqlanmaydi. Parol yoki karta raqamini yubormang.",
        "consent": "Roziman", "consented": "Tayyor. Ovozli xabar yoki matn yuboring.",
        "confirm": "✅ Tasdiqlash", "edit": "✏️ Tahrirlash", "cancel": "❌ Bekor qilish",
        "processing": "🎧 Qabul qilindi, tahlil qilyapman…", "ready": "Shunday bajarilsinmi? Hali hech narsa o‘zgarmadi.",
        "draft": "Hali hech narsa bajarilmadi.",
        "executed": "✅ Tasdiqlandi", "cancelled": "❌ Bekor qilindi",
        "edit_prompt": "Tuzatishni matn yoki ovoz bilan yuboring. Masalan: «Ertaga emas, juma kuni soat 10 da».",
        "private": "Ovozli yordamchidan bot bilan shaxsiy chatda foydalaning.", "heard": "Siz aytdingiz",
        "wrong_language": "Iltimos, o‘zbek tilida gapiring. Tilni sozlamalarda o‘zgartirish mumkin.",
        "clarify": "Tushunmadim. Nima qilish kerakligini aniqroq ayting.",
        "disabled": "Ovozli yordamchi hali yoqilmagan.",
        "failure": "Bajarilmadi. Qayta urinib ko‘ring.",
        "provider_limit": "Bepul AI limiti hozircha tugadi. 1 daqiqadan keyin qayta yuboring; kunlik limit tugagan bo‘lsa — ertaga.",
        "daily_limit": "Bugungi limitingiz tugadi. Ertaga davom etamiz.",
        "plan_limit": "Bu imkoniyat Pro tarifda. Bepul tarifda ovozli buyruqlar haftasiga 5 ta.",
        "provider_not_configured": "AI kaliti ulanmagan. Administratorga ayting.",
        "provider_unavailable": "AI xizmati javob bermadi. Qayta urinib ko‘ring.",
        "consent_required": "Avval /agent orqali rozilik bering.",
        "stale_draft": "Bu eski tugma. Oxirgi taklifdan foydalaning.",
        "stale_target": "Yozuv o‘zgargan. Buyruqni qaytadan yuboring.",
        "timer_required": "Bu taymer bilan bajariladi — avval taymerni ishga tushiring yoki ilovada «Taymersiz bajardim» deb yozing.",
        "not_found": "Yozuv topilmadi.", "forbidden": "Bu jamoa yozuvini o‘zgartirishga ruxsatingiz yo‘q.",
        "protected_item": "Bu odat o‘z bo‘limidan boshqariladi.",
        "draft_expired": "Taklif eskirdi (24 soat). Buyruqni qaytadan yuboring.",
        "audio_too_long": "Audio 2 daqiqadan oshmasin.", "invalid_audio": "Audio o‘qilmadi. Qaytadan yozib yuboring.",
        "audio_decoder_missing": "Serverda audio o‘quvchi yo‘q. Matn yuboring.",
        "empty_audio": "Ovozdan matn olinmadi. Qaytadan yozing.",
        "invalid_plan": "Buyruqni tushunmadim. Aniqroq ayting.",
        "processing_interrupted": "Tahlil uzildi. Qaytadan yuboring.",
        "not_ready": "Bu taklifni tasdiqlab bo‘lmaydi.",
        "invalid_text": "Matn bo‘sh bo‘lmasin va 6000 belgidan oshmasin.",
        "invalid_fields": "Sana, vaqt yoki summa noto‘g‘ri. Aniqroq ayting.",
        "missing_fields": "Ma’lumot yetishmayapti: nomi, summasi yoki kirim/chiqimligini ayting.",
        "invalid_action": "Bu amalni bajarib bo‘lmaydi.",
        "unknown_reference": "Qaysi yozuv nazarda tutilgani aniq emas. Nomini aniqroq ayting.",
        "invalid_day": "Sana kelajakda yoki bir yildan eski bo‘lmasin.",
        "duplicate_target": "Bitta yozuvga bir nechta amal tushdi. Bittasini ayting.",
        "too_many_edits": "Tuzatishlar ko‘payib ketdi. Buyruqni yangidan yuboring.",
        "concurrent_change": "Boshqa o‘zgarish bilan to‘qnashdi. Qayta urinib ko‘ring.",
    },
    "ru": {
        "welcome": "🎙 Ernest — голосовой помощник\nОтправьте голосовое или текст: добавлю, изменю или удалю задачу, привычку, проект или запись финансов. Выполняю только после кнопки «Подтвердить».\n\nГолос и текст передаются AI-сервисам (ElevenLabs, Groq, Google — США). Аудио не хранится. Не отправляйте пароли и номера карт.",
        "consent": "Согласен", "consented": "Готово. Отправьте голосовое или текст.",
        "confirm": "✅ Подтвердить", "edit": "✏️ Исправить", "cancel": "❌ Отменить",
        "processing": "🎧 Принято, обрабатываю…", "ready": "Выполнить так? Пока ничего не изменено.",
        "draft": "Пока ничего не выполнено.",
        "executed": "✅ Подтверждено", "cancelled": "❌ Отменено",
        "edit_prompt": "Отправьте исправление текстом или голосом. Например: «Не завтра, а в пятницу в 10».",
        "private": "Используйте помощника в личном чате с ботом.", "heard": "Вы сказали",
        "wrong_language": "Пожалуйста, говорите по-русски. Язык можно сменить в настройках.",
        "clarify": "Не понял. Уточните, что нужно сделать.",
        "disabled": "Голосовой помощник пока выключен.",
        "failure": "Не выполнено. Попробуйте ещё раз.",
        "provider_limit": "Бесплатный лимит AI сейчас исчерпан. Повторите через минуту; если исчерпан дневной — завтра.",
        "daily_limit": "Ваш дневной лимит исчерпан. Продолжим завтра.",
        "plan_limit": "Это доступно на тарифе Pro. На бесплатном — 5 голосовых команд в неделю.",
        "provider_not_configured": "Ключ AI не подключён. Сообщите администратору.",
        "provider_unavailable": "AI не ответил. Попробуйте ещё раз.",
        "consent_required": "Сначала дайте согласие через /agent.",
        "stale_draft": "Это старая кнопка. Используйте последнее предложение.",
        "stale_target": "Запись изменилась. Отправьте команду заново.",
        "timer_required": "Это выполняется по таймеру — запустите таймер или запишите время в приложении («Сделал без таймера»).",
        "not_found": "Запись не найдена.", "forbidden": "Нет прав менять эту командную запись.",
        "protected_item": "Эта привычка управляется в своём разделе.",
        "draft_expired": "Предложение устарело (24 часа). Отправьте команду заново.",
        "audio_too_long": "Аудио не длиннее 2 минут.", "invalid_audio": "Не удалось прочитать аудио. Запишите заново.",
        "audio_decoder_missing": "На сервере нет аудиодекодера. Отправьте текст.",
        "empty_audio": "Речь не распознана. Запишите заново.",
        "invalid_plan": "Не понял команду. Скажите точнее.",
        "processing_interrupted": "Обработка прервана. Отправьте заново.",
        "not_ready": "Это предложение нельзя подтвердить.",
        "invalid_text": "Текст не пустой и не длиннее 6000 символов.",
        "invalid_fields": "Неверная дата, время или сумма. Скажите точнее.",
        "missing_fields": "Не хватает данных: название, сумма или доход/расход.",
        "invalid_action": "Это действие недоступно.",
        "unknown_reference": "Непонятно, какая запись имеется в виду. Назовите точнее.",
        "invalid_day": "Дата не в будущем и не старше года.",
        "duplicate_target": "Несколько действий для одной записи. Назовите одно.",
        "too_many_edits": "Слишком много исправлений. Отправьте команду заново.",
        "concurrent_change": "Конфликт с другим изменением. Попробуйте ещё раз.",
    },
    "en": {
        "welcome": "🎙 Ernest voice assistant\nSend a voice message or text: I add, edit or delete tasks, habits, projects and money entries. Nothing runs until you press Confirm.\n\nVoice and text are sent to AI services (ElevenLabs, Groq, Google — USA). Audio is not stored. Do not send passwords or card numbers.",
        "consent": "I agree", "consented": "Ready. Send a voice message or text.",
        "confirm": "✅ Confirm", "edit": "✏️ Edit", "cancel": "❌ Cancel",
        "processing": "🎧 Received, analyzing…", "ready": "Proceed with this? Nothing has changed yet.",
        "draft": "Nothing has been executed yet.",
        "executed": "✅ Confirmed", "cancelled": "❌ Cancelled",
        "edit_prompt": "Send the correction as text or voice, e.g. 'Friday at 10, not tomorrow'.",
        "private": "Please use the assistant in a private chat with the bot.", "heard": "You said",
        "wrong_language": "Please speak English. You can change the language in settings.",
        "clarify": "I didn't understand. Say more precisely what to do.",
        "disabled": "The voice assistant is not enabled yet.",
        "failure": "Not executed. Please try again.",
        "provider_limit": "The free AI quota is used up for now. Try again in a minute; if the daily quota is gone, tomorrow.",
        "daily_limit": "Your daily limit is used up. See you tomorrow.",
        "plan_limit": "This is part of Pro. The Free plan has 5 voice commands a week.",
        "provider_not_configured": "AI key is not configured. Tell the administrator.",
        "provider_unavailable": "AI did not respond. Please try again.",
        "consent_required": "Give consent through /agent first.",
        "stale_draft": "This button is outdated. Use the latest proposal.",
        "stale_target": "The record changed. Send the command again.",
        "timer_required": "This one is done by its timer — start it, or log the time in the app («Did it without the timer»).",
        "not_found": "Record not found.", "forbidden": "You cannot change this team record.",
        "protected_item": "This habit is managed on its own screen.",
        "draft_expired": "The proposal expired (24 hours). Send the command again.",
        "audio_too_long": "Audio must be 2 minutes or shorter.", "invalid_audio": "Cannot read the audio. Record it again.",
        "audio_decoder_missing": "Server audio decoder is missing. Send text.",
        "empty_audio": "No speech recognized. Record again.",
        "invalid_plan": "I didn't understand the command. Be more specific.",
        "processing_interrupted": "Processing was interrupted. Send it again.",
        "not_ready": "This proposal cannot be confirmed.",
        "invalid_text": "Text must be non-empty and at most 6000 characters.",
        "invalid_fields": "Invalid date, time or amount. Be more specific.",
        "missing_fields": "Missing information: name, amount or income/expense.",
        "invalid_action": "This action is not available.",
        "unknown_reference": "Unclear which record you mean. Name it more precisely.",
        "invalid_day": "Date cannot be in the future or over a year ago.",
        "duplicate_target": "Several actions target one record. Name one.",
        "too_many_edits": "Too many corrections. Send the command again.",
        "concurrent_change": "Conflict with another change. Please try again.",
    },
}


def tr(lang, key):
    words = TEXT.get(lang, TEXT["uz"])
    return words.get("disabled" if key == "agent_disabled" else key, words["failure"])
